/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import command.Message;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Izzuddin
 */
public class client extends javax.swing.JFrame {

    /**
     * Creates new form client
     */
    private Socket server = null;
    private BufferedOutputStream bos = null;
    private BufferedInputStream bis = null;
    private ObjectOutputStream oos = null;
    private ObjectInputStream ois = null;
    private FileInputStream fis = null;
    private FileOutputStream fos = null;
    private File f;
    private ArrayList<String> rcpt = new ArrayList<>();
    private String secret;
    private StringBuffer dashes;
    private final int MAXPARTS = 6;
    private int bodyparts;
    private boolean done;
    private String guess;
    private String guesses;
    private char letter;
    private Scanner infile;
    private threadReadClient trdClient;
    private String currentWord;

    /**
     *
     */
    public client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connBtn = new javax.swing.JButton();
        diconnBtn = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgPool = new javax.swing.JTextArea();
        sendBtn = new javax.swing.JButton();
        sendText = new javax.swing.JTextField();
        guessText = new javax.swing.JTextField();
        guessBtn = new javax.swing.JButton();
        words = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        connBtn.setText("Connect");
        connBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connBtnActionPerformed(evt);
            }
        });

        diconnBtn.setText("Disconnect");
        diconnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diconnBtnActionPerformed(evt);
            }
        });

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/img/1.png"))); // NOI18N
        img.setText("jLabel1");

        jButton1.setText("chg");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        msgPool.setColumns(20);
        msgPool.setRows(5);
        jScrollPane1.setViewportView(msgPool);

        sendBtn.setText("send");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        sendText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendTextActionPerformed(evt);
            }
        });

        guessText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessTextActionPerformed(evt);
            }
        });

        guessBtn.setText("guess");
        guessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessBtnActionPerformed(evt);
            }
        });

        words.setFont(new java.awt.Font("Tahoma", 0, 42)); // NOI18N
        words.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        words.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        words.setEnabled(false);

        uname.setText("udin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(connBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diconnBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(guessText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guessBtn))
                            .addComponent(img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(words, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sendText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendBtn)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(words, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guessBtn)
                    .addComponent(sendBtn)
                    .addComponent(sendText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diconnBtn)
                    .addComponent(connBtn)
                    .addComponent(jButton1)
                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        words.getAccessibleContext().setAccessibleName("words");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connBtnActionPerformed
        try {
            server = new Socket("localhost", 6060);
            bos = new BufferedOutputStream(server.getOutputStream());
            oos = new ObjectOutputStream(server.getOutputStream());
            ois = new ObjectInputStream(server.getInputStream());
            this.trdClient = new threadReadClient(this, server, ois, this.msgPool);
            this.trdClient.start();
            command.CommandList baru = new command.CommandList();

            baru.setCommand("START");
            oos.writeObject(baru);
            oos.flush();
            //StartGame();
            System.out.println(getCurrentWord() + "haha");

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Server sedang offline");
        }

    }//GEN-LAST:event_connBtnActionPerformed

    private void diconnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diconnBtnActionPerformed
        try {
            command.CommandList baru = new command.CommandList();
            baru.setCommand("END");
            oos.writeObject(baru);
            oos.flush();

            ois.close();
            oos.close();
            server.close();
        } catch (IOException ex) {
            Logger.getLogger(client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_diconnBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StartGame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessBtnActionPerformed
        guess = guessText.getText();
        letter = guess.charAt(0);
        guesses += letter;
        if (secret.indexOf(letter) < 0) // not there
        {
            --bodyparts;
            System.out.print("bad guess - ");
            img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/img/" + (6 - bodyparts + 1) + ".png")));
        } else // letter is in the secret
        {
            //	put it in dashes where it belongs
            matchLetter(secret, dashes, letter, words);
        }
        System.out.println(bodyparts + " bodyparts are left");
        if (bodyparts == 0) {
            System.out.println("you lose");
            done = true;
        }
        if (secret.equals(dashes.toString())) {
            System.out.println("you win!");
            done = true;
        }
        guessText.setText("");
    }//GEN-LAST:event_guessBtnActionPerformed

    private void guessTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessTextActionPerformed
        guessBtnActionPerformed(evt);
    }//GEN-LAST:event_guessTextActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        try {
            Message pesan = new Message();
            pesan.setIsi(sendText.getText());
            pesan.setDari(uname.getText());
            oos.writeObject(pesan);
            oos.flush();
            oos.reset();

            this.sendText.setText("");
        } catch (IOException ex) {
            Logger.getLogger(client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendBtnActionPerformed

    private void sendTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendTextActionPerformed
        sendBtnActionPerformed(evt);
    }//GEN-LAST:event_sendTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new client().setVisible(true);
            }
        });
    }

    public static void matchLetter(String secret, StringBuffer dashes, char letter, JLabel words) {
        for (int index = 0; index < secret.length(); index++) {
            if (secret.charAt(index) == letter) {
                dashes.setCharAt(index, letter);
            }
        }
        System.out.print("good guess - ");
        words.setText(dashes.toString());
    }

    public static StringBuffer makeDashes(String s) {
        StringBuffer dashes = new StringBuffer(s.length());
        for (int count = 0; count < s.length(); count++) {
            dashes.append('-');
        }
        return dashes;
    }

    public void StartGame() {
        secret = getCurrentWord();
        guesses = "";
        done = false;
        bodyparts = MAXPARTS;
        System.out.println(secret);
        dashes = makeDashes(secret);
        words.setText(dashes.toString());
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/img/1.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connBtn;
    private javax.swing.JButton diconnBtn;
    private javax.swing.JButton guessBtn;
    private javax.swing.JTextField guessText;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea msgPool;
    private javax.swing.JButton sendBtn;
    private javax.swing.JTextField sendText;
    private javax.swing.JTextField uname;
    private javax.swing.JLabel words;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the currentWord
     */
    public String getCurrentWord() {
        return currentWord;
    }

    /**
     * @param currentWord the currentWord to set
     */
    public void setCurrentWord(String currentWord) {
        this.currentWord = currentWord;
    }
}
